theme: jekyll-theme-minimal
title: Discussion of Random Projection Ensemble Classification
description: "Authors: Wicher Bergsma and Haziq Jamil. London School of Economics and Political Science. March 30, 2017."
